### ISSUE TITLE
Less accurate

### ISSUE THREAD

**Issue by Zumbalamambo** [datitran/object_detector_app#27] opened 2017-09-18 18:39 UTC
I trained the model to detect various shapes say triangle , circle. The detection is less accurate. I used aroudn 5000 images per class. the detection is not accurate and it is jumping.

**Comment by datitran** [comment] 2017-09-19 00:06
And? Have you checked your mAP yet? Maybe you just need to use another model.

**Comment by Zumbalamambo** [comment] 2017-09-21 03:15
May i know what is mAP?

**Comment by Zumbalamambo** [comment] 2017-09-21 03:15
which model will you suggest for shapes detection?

**Comment by datitran** [comment] 2017-09-24 17:27
mAP is mean average precision. Concerning the model question, I would suggest to ask this question on Stackoverflow. Since it is not a bug or an issue I will close this one.

**Closed as completed by datitran** 2017-09-24 17:27 UTC
